#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Galaxy S9"
#define BTM_BYPASS_EXTRA_ACL_SETUP TRUE

#define BTM_WBS_INCLUDED TRUE
#define BTIF_HF_WBS_PREFERRED TRUE

#define BLE_INCLUDED TRUE
#define BLE_VND_INCLUDED TRUE

#endif
